# Generated by Django 2.2.12 on 2020-06-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_instagram', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('access_token', models.CharField(max_length=120)),
            ],
        ),
    ]
